services:
  db:
    image: postgres:13.6
    container_name: postgresql
    ports:
      - 5432:5432
    volumes:
      - type: bind
        source: './postgresql/db-store'
        target: '/var/lib/postgresql/data'
      - type: bind
        source: './postgresql/script'
        target: '/docker-entrypoint-initdb.d'
    environment:
      - POSTGRES_PASSWORD=passwordsw23ed

  mq:
    build:
      context: .
      dockerfile: ./activemq/Dockerfile
    ports:
      - 8161:8161
